version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: woke_test
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: woke_test_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
